### ISSUE TITLE
up for requests?

### ISSUE THREAD

**Issue by sungo** [camrbuss/crkbd-curvy-sandwich#1]
I just completed a build of one half of a corne. I have thoughts :) Are you up for a couple requests that i lack the skill currently to do myself? Totally cool if not but I wanted to check first.

**Comment by camrbuss** [comment]
Depends a little bit on the request, but I am certainly open. Feel free to add them here.

**Comment by sungo** [comment]
Excellent. Thank you :) Two things came to mind.

First, I was considering a bottom plate that is the same size as the “thin” layers. 

Second, a version of the top plate that protects the MCU that has holes big enough that it could serve as a middle layer. The use case there is I don’t install oleds on my personal builds. Two of those layers would seal up the MCU pretty nicely. And maintain the height of the case.

Thank you for considering my requests. This case is almost exactly what I was trying and failing to design myself.

**Comment by camrbuss** [comment]
I don't know if I feel like changing the bottom plate "width" as I quiet like the aesthetic of 0, and 1 being a little bit wider. You are welcome to change it in Solvespace yourself though.

When you say top plate, do you mean switchplate? Can you use the numbers/names of the files in the repo? The 4 plate cannot cover up the 3.5mm jack due to its height, but could cover some of the MCU area. Why wouldn't you just cut plate number 7 is an opaque color and call it a day?

**Comment by sungo** [comment]
For plate 0, I was thinking of having an additional option, not replacing the current. But understood.

When I say "top plate", I mean file 7. As designed, the upper levels of the sandwich look like files 4, 5, 5, 7. With how I build crkbd, it's possible I think to sandwich as 4, 7, 5, 5 or something similar. Layering file 7 after file 4 (the switch plate) I think will completely cover up the hole above the MCU with no other problems. There just needs to be a version of file 7 with screw holes big enough to hold standoffs.

**Comment by sungo** [comment]
I'll try to make these modifications on my own. Thanks for being willing to consider them :)

**Comment by camrbuss** [comment]
Thanks for the clarification. I think you could squeeze 7 on top of 4. I actually just enlarged the holes on 7 for you up to 3.2mm. It was just one sketch edit.
![7-clear_cover_3 2mm](https://user-images.githubusercontent.com/13991695/153529239-62e2668c-9e7b-4724-b89e-0697af651345.svg)

**Comment by sungo** [comment]
oh excellent. Thank you :) Solvespace and I have not come to an understanding yet.

**Comment by camrbuss** [comment]
Its a little tough. Watch out for your 3.5mm headphone jack clearance if you do try out this idea. On my build the jack is slightly above the switchplate. 

Oh, also watch out for USB clearance with the bottom plate, you may want to use Inkscape to add a cutout for the USB jack if your cable is not slim.
